// AUTO-GENERATED by supabase/scripts/bundle_for_deploy.mjs
// Do not edit directly - edit the source files and rerun the script.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

// ---- inlined from _shared/cors.ts ----
// Cabeceras CORS compartidas por todas las Edge Functions
// Restringido al origen de producción + localhost dev
const ALLOWED_ORIGINS = [
  "http://localhost:3000",
  "https://clinica-almudena.vercel.app",
  Deno.env.get("FRONTEND_URL") ?? "",
].filter(Boolean);

function buildCorsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}

function handleOptions(req: Request): Response | null {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: buildCorsHeaders(req.headers.get("origin")),
    });
  }
  return null;
}


// ---- inlined from _shared/stripe.ts ----
// Cliente Stripe minimalista (REST API directa, sin SDK).
// Evitamos el SDK oficial para minimizar cold-start y superficie de dependencias.

const STRIPE_API = "https://api.stripe.com/v1";

interface StripeError { error?: { message?: string; code?: string; type?: string } }

class StripeApiError extends Error {
  public code: string | undefined;
  public status: number;
  constructor(status: number, message: string, code?: string) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

function apiKey(): string {
  const k = Deno.env.get("STRIPE_SECRET_KEY");
  if (!k) throw new StripeApiError(500, "STRIPE_SECRET_KEY no configurado");
  return k;
}

function encodeForm(obj: Record<string, unknown>, prefix = ""): string {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;
    const k = prefix ? `${prefix}[${key}]` : key;
    if (Array.isArray(value)) {
      value.forEach((v, i) => {
        if (typeof v === "object" && v !== null) {
          parts.push(encodeForm(v as Record<string, unknown>, `${k}[${i}]`));
        } else {
          parts.push(`${encodeURIComponent(`${k}[${i}]`)}=${encodeURIComponent(String(v))}`);
        }
      });
    } else if (typeof value === "object") {
      parts.push(encodeForm(value as Record<string, unknown>, k));
    } else {
      parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(value))}`);
    }
  }
  return parts.filter(Boolean).join("&");
}

async function stripeRequest<T>(
  path: string,
  method: "GET" | "POST",
  body?: Record<string, unknown>,
  idempotencyKey?: string,
): Promise<T> {
  const headers: Record<string, string> = {
    Authorization: `Bearer ${apiKey()}`,
  };
  if (method === "POST") {
    headers["Content-Type"] = "application/x-www-form-urlencoded";
  }
  if (idempotencyKey) {
    headers["Idempotency-Key"] = idempotencyKey;
  }

  const res = await fetch(`${STRIPE_API}${path}`, {
    method,
    headers,
    body: body ? encodeForm(body) : undefined,
  });

  if (!res.ok) {
    const err = (await res.json().catch(() => ({}))) as StripeError;
    throw new StripeApiError(
      res.status,
      err.error?.message ?? `stripe ${res.status}`,
      err.error?.code,
    );
  }

  return (await res.json()) as T;
}

// ---------------------------------------------------------------------------
// Checkout Sessions
// ---------------------------------------------------------------------------

interface CheckoutLineItem {
  name: string;
  description?: string;
  amount_centimos: number;
  quantity?: number;
}

interface CreateCheckoutInput {
  customer_email: string;
  success_url: string;
  cancel_url: string;
  client_reference_id?: string;
  metadata: Record<string, string>;
  line_items: CheckoutLineItem[];
  idempotency_key: string;
  /**
   * Si se omite o es true, Stripe elige automáticamente todos los métodos
   * habilitados en Dashboard (card + Apple/Google Pay + Klarna + Bizum...).
   * Si se pasa un array, se usa `payment_method_types` explícito.
   */
  payment_method_types?: string[];
  automatic_payment_methods?: boolean;
  locale?: string;
}

interface CheckoutSession {
  id: string;
  url: string;
  payment_intent: string | null;
  customer: string | null;
  payment_status: string;
  amount_total: number;
  currency: string;
  metadata?: Record<string, string>;
}

async function createCheckoutSession(
  input: CreateCheckoutInput,
): Promise<CheckoutSession> {
  const usarAuto =
    input.automatic_payment_methods ??
    (input.payment_method_types === undefined);

  const body: Record<string, unknown> = {
    mode: "payment",
    customer_email: input.customer_email,
    success_url: input.success_url,
    cancel_url: input.cancel_url,
    client_reference_id: input.client_reference_id,
    locale: input.locale ?? "es",
    metadata: input.metadata,
    line_items: input.line_items.map((it) => ({
      price_data: {
        currency: "eur",
        unit_amount: it.amount_centimos,
        product_data: {
          name: it.name,
          description: it.description ?? undefined,
        },
      },
      quantity: it.quantity ?? 1,
    })),
  };

  // Métodos de pago: auto (wallets + Klarna) o lista explícita.
  if (usarAuto) {
    body["automatic_payment_methods[enabled]"] = "true";
    body["automatic_payment_methods[allow_redirects]"] = "always";
  } else if (input.payment_method_types && input.payment_method_types.length > 0) {
    body.payment_method_types = input.payment_method_types;
  }

  // metadata también dentro del PaymentIntent (para que el webhook lo tenga
  // accesible tanto si escuchamos checkout.session.completed como
  // payment_intent.succeeded).
  for (const [k, v] of Object.entries(input.metadata)) {
    body[`payment_intent_data[metadata][${k}]`] = v;
  }

  return await stripeRequest<CheckoutSession>(
    "/checkout/sessions",
    "POST",
    body,
    input.idempotency_key,
  );
}

// ---------------------------------------------------------------------------
// PaymentIntents (para Payment Element embebido)
// ---------------------------------------------------------------------------

interface CreatePaymentIntentInput {
  amount_centimos: number;
  currency?: string;                    // 'eur' por defecto
  customer_email: string;
  description?: string;
  metadata: Record<string, string>;
  idempotency_key: string;
  /** Si true → automatic_payment_methods + allow_redirects=always (Klarna, etc). */
  automatic_payment_methods?: boolean;
  /** Si se omite, se usa la moneda por defecto (EUR). */
  receipt_email?: string;
}

interface PaymentIntent {
  id: string;
  client_secret: string;
  status: string;
  amount: number;
  currency: string;
  metadata?: Record<string, string>;
}

async function createPaymentIntent(
  input: CreatePaymentIntentInput
): Promise<PaymentIntent> {
  const body: Record<string, unknown> = {
    amount: input.amount_centimos,
    currency: input.currency ?? "eur",
    receipt_email: input.receipt_email ?? input.customer_email,
    description: input.description,
    metadata: input.metadata,
  };

  const auto = input.automatic_payment_methods ?? true;
  if (auto) {
    body["automatic_payment_methods[enabled]"] = "true";
    body["automatic_payment_methods[allow_redirects]"] = "always";
  }

  return await stripeRequest<PaymentIntent>(
    "/payment_intents",
    "POST",
    body,
    input.idempotency_key
  );
}

// ---------------------------------------------------------------------------
// Refunds
// ---------------------------------------------------------------------------

interface CreateRefundInput {
  payment_intent: string;
  amount_centimos?: number;        // null = refund total
  reason?: "duplicate" | "fraudulent" | "requested_by_customer";
  idempotency_key: string;
  metadata?: Record<string, string>;
}

interface StripeRefund {
  id: string;
  amount: number;
  currency: string;
  status: string;          // 'succeeded' | 'pending' | 'failed' | 'requires_action'
  payment_intent: string;
  reason?: string | null;
}

async function createRefund(input: CreateRefundInput): Promise<StripeRefund> {
  const body: Record<string, unknown> = {
    payment_intent: input.payment_intent,
    reason: input.reason ?? "requested_by_customer",
  };
  if (typeof input.amount_centimos === "number" && input.amount_centimos > 0) {
    body.amount = input.amount_centimos;
  }
  if (input.metadata) {
    for (const [k, v] of Object.entries(input.metadata)) {
      body[`metadata[${k}]`] = v;
    }
  }
  return await stripeRequest<StripeRefund>("/refunds", "POST", body, input.idempotency_key);
}

// ---------------------------------------------------------------------------
// Webhook signature verification (Stripe spec)
// ---------------------------------------------------------------------------

interface ParsedSignatureHeader {
  timestamp: number;
  signatures: string[];
}

function parseSignatureHeader(header: string): ParsedSignatureHeader | null {
  const parts = header.split(",").map((s) => s.trim());
  let timestamp = 0;
  const signatures: string[] = [];
  for (const p of parts) {
    const [k, v] = p.split("=");
    if (!k || !v) continue;
    if (k === "t") timestamp = Number(v);
    else if (k === "v1") signatures.push(v);
  }
  if (!timestamp || signatures.length === 0) return null;
  return { timestamp, signatures };
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/**
 * Verifica la firma del webhook según la especificación oficial de Stripe.
 * Tolerancia de 5 minutos para prevenir replay attacks.
 * @returns el evento parseado si es válido, o null si no lo es.
 */
async function verifyWebhookSignature(
  rawBody: string,
  sigHeader: string | null,
  secret: string,
  toleranceSeconds = 300,
): Promise<unknown | null> {
  if (!sigHeader) return null;
  const parsed = parseSignatureHeader(sigHeader);
  if (!parsed) return null;

  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - parsed.timestamp) > toleranceSeconds) return null;

  const payload = `${parsed.timestamp}.${rawBody}`;

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(payload),
  );
  const expectedHex = bytesToHex(new Uint8Array(signature));

  const match = parsed.signatures.some((s) => timingSafeEqual(s, expectedHex));
  if (!match) return null;

  try {
    return JSON.parse(rawBody);
  } catch {
    return null;
  }
}


// ---- main function body ----
// Edge Function: stripe-checkout
// -----------------------------------------------------------------------------
// Crea una sesión Checkout de Stripe para dos casos:
//   1. Pago de cita suelta (sin bono activo)  → body { kind: "cita", cita_id }
//   2. Compra de bono                          → body { kind: "bono", bono_config_id }
//
// Security:
//   * Valida JWT del usuario (authenticated) para obtener user_id.
//   * Llama a RPC SECURITY DEFINER (preparar_checkout_*) que valida ownership.
//   * STRIPE_SECRET_KEY vive SOLO en env de esta función.
// -----------------------------------------------------------------------------


const FRONTEND_URL = Deno.env.get("FRONTEND_URL") ?? "https://clinica-almudena.vercel.app";

interface CheckoutRequest {
  kind: "cita" | "bono";
  cita_id?: string;
  bono_config_id?: string;
}

interface CitaCtx {
  cita_id: string;
  inicio: string;
  servicio_nombre: string;
  importe_centimos: number;
  email: string;
  display_name: string | null;
}

interface BonoCtx {
  bono_config_id: string;
  nombre: string;
  descripcion: string | null;
  sesiones: number;
  importe_centimos: number;
  email: string;
  display_name: string | null;
}

function json(body: unknown, status: number, cors: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, "Content-Type": "application/json" },
  });
}

const UUID_RE = /^[0-9a-f-]{36}$/i;

Deno.serve(async (req) => {
  const cors = buildCorsHeaders(req.headers.get("origin"));
  const opts = handleOptions(req);
  if (opts) return opts;

  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405, cors);

  const authHeader = req.headers.get("authorization");
  if (!authHeader) return json({ error: "unauthorized" }, 401, cors);

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

  // Cliente autenticado con el JWT del usuario (para getUser)
  const supabaseAuth = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });

  const { data: { user }, error: authErr } = await supabaseAuth.auth.getUser();
  if (authErr || !user) return json({ error: "unauthorized" }, 401, cors);

  let payload: CheckoutRequest;
  try {
    payload = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400, cors);
  }

  // Cliente con service_role para RPCs SECURITY DEFINER
  const admin = createClient(supabaseUrl, serviceKey, {
    auth: { persistSession: false },
  });

  try {
    if (payload.kind === "cita") {
      if (!payload.cita_id || !UUID_RE.test(payload.cita_id)) {
        return json({ error: "missing_cita_id" }, 400, cors);
      }

      const { data, error } = await admin.rpc("preparar_checkout_cita", {
        p_cita_id: payload.cita_id,
        p_user_id: user.id,
      });
      if (error) return json({ error: "rpc_failed", detail: error.message }, 500, cors);

      const ctx = (Array.isArray(data) ? data[0] : data) as CitaCtx | null;
      if (!ctx) return json({ error: "cita_not_found_or_not_owned" }, 404, cors);

      const session = await createCheckoutSession({
        customer_email: ctx.email,
        success_url: `${FRONTEND_URL}/portal/pagos/success?session_id={CHECKOUT_SESSION_ID}`,
        cancel_url: `${FRONTEND_URL}/portal/pagos/cancel?cita_id=${ctx.cita_id}`,
        client_reference_id: ctx.cita_id,
        metadata: {
          kind: "cita",
          cita_id: ctx.cita_id,
          user_id: user.id,
        },
        line_items: [{
          name: `Sesión — ${ctx.servicio_nombre}`,
          description: `Fecha: ${new Date(ctx.inicio).toLocaleString("es-ES", { dateStyle: "full", timeStyle: "short", timeZone: "Europe/Madrid" })}`,
          amount_centimos: ctx.importe_centimos,
          quantity: 1,
        }],
        automatic_payment_methods: true,
        locale: "es",
        idempotency_key: `cita-${ctx.cita_id}-${user.id}`,
      });

      return json({ url: session.url, session_id: session.id }, 200, cors);
    }

    if (payload.kind === "bono") {
      if (!payload.bono_config_id || !UUID_RE.test(payload.bono_config_id)) {
        return json({ error: "missing_bono_config_id" }, 400, cors);
      }

      const { data, error } = await admin.rpc("preparar_checkout_bono", {
        p_bono_config_id: payload.bono_config_id,
        p_user_id: user.id,
      });
      if (error) return json({ error: "rpc_failed", detail: error.message }, 500, cors);

      const ctx = (Array.isArray(data) ? data[0] : data) as BonoCtx | null;
      if (!ctx) return json({ error: "bono_not_found_or_not_owned" }, 404, cors);

      const idempotencyKey = `bono-${ctx.bono_config_id}-${user.id}-${Date.now()}`;

      const session = await createCheckoutSession({
        customer_email: ctx.email,
        success_url: `${FRONTEND_URL}/portal/pagos/success?session_id={CHECKOUT_SESSION_ID}`,
        cancel_url: `${FRONTEND_URL}/portal/pagos/cancel`,
        metadata: {
          kind: "bono",
          bono_config_id: ctx.bono_config_id,
          user_id: user.id,
        },
        line_items: [{
          name: ctx.nombre,
          description: ctx.descripcion ?? `${ctx.sesiones} sesiones`,
          amount_centimos: ctx.importe_centimos,
          quantity: 1,
        }],
        automatic_payment_methods: true,
        locale: "es",
        idempotency_key: idempotencyKey,
      });

      return json({ url: session.url, session_id: session.id }, 200, cors);
    }

    return json({ error: "unknown_kind" }, 400, cors);
  } catch (err) {
    if (err instanceof StripeApiError) {
      return json({ error: "stripe_error", detail: err.message, code: err.code }, 502, cors);
    }
    const msg = err instanceof Error ? err.message : String(err);
    return json({ error: "internal", detail: msg }, 500, cors);
  }
});
