import { clinicPrimaryKeywordsList } from './primary-keywords';
import { clinicStripePaymentKeywordsList } from './stripe-payment-keywords';

/**
 * Palabras clave extendidas solo para la home: intención de búsqueda local y servicios.
 * Se usan en `metadata.keywords` y en JSON-LD `WebPage.keywords` (schema.org).
 */
const HOME_EXTENDED_SEARCH_KEYWORDS = [
  'Almudena Marchesi',
  'Psicóloga',
  'Clinica de Psicología',
  'Clínica de Psicología Madrid',
  'Clínica de Psicología Chamberí',
  'Clínica de Psicología Argüelles',
  'Clínica de Psicología Moncloa',
  'psicologa',
  'psicóloga Madrid',
  'psicóloga Chamberí',
  'psicóloga Argüelles',
  'psicóloga Moncloa',
  'psicologo',
  'psicólogo Chamberí',
  'psicólogo Argüelles',
  'psicólogo Moncloa',
  'terapia',
  'terapia Madrid',
  'terapia Chamberí',
  'terapia Argüelles',
  'terapia Moncloa',
  'terapia individal',
  'terapia individual Madrid',
  'terapia individual Chamberí',
  'terapia individual Argüelles',
  'terapia individual Moncloa',
  'terapia ansiedad',
  'terapia ansiedad Madrid',
  'terapia ansiedad Chamberí',
  'terapia ansiedad Argüelles',
  'terapia ansiedad Moncloa',
  'terapia de pareja',
  'terapia de pareja Madrid',
  'terapia de pareja Chamberí',
  'terapia de pareja Argüelles',
  'terapia de pareja Moncloa',
  'terapia infantil',
  'terapia infantil Madrid',
  'terapia infantil Chamberí',
  'terapia infantil Argüelles',
  'terapia infantil Moncloa',
  'terapia online',
  'terapia online Madrid',
  'terapia online Chamberí',
  'terapia online Argüelles',
  'terapia online Moncloa',
  'terapia depresion',
  'terapia depresion Madrid',
  'terapia depresion Chamberí',
  'terapia depresion Argüelles',
  'terapia depresion Moncloa',
  'terapia depresion individual',
  'terapia depresion individual Madrid',
  'terapia depresion individual Chamberí',
  'terapia depresion individual Argüelles',
  'terapia depresion individual Moncloa',
  'terapia depresion de pareja',
  'terapia depresion de pareja Madrid',
  'terapia depresion de pareja Chamberí',
  'terapia depresion de pareja Argüelles',
  'terapia depresion de pareja Moncloa',
  'terapia depresion infantil',
  'terapia depresion infantil Madrid',
  'terapia depresion infantil Chamberí',
  'terapia depresion infantil Argüelles',
  'terapia depresion infantil Moncloa',
  'terapia depresion online',
  'terapia depresion online Madrid',
  'terapia depresion online Chamberí',
  'terapia depresion online Argüelles',
  'terapia depresion online Moncloa',
  'terapia depresion ansiedad',
  'terapia depresion ansiedad Madrid',
  'terapia depresion ansiedad Chamberí',
  'terapia depresion ansiedad Argüelles',
  'terapia depresion ansiedad Moncloa',
  'terapia depresion ansiedad individual',
  'terapia depresion ansiedad individual Madrid',
  'terapia depresion ansiedad individual Chamberí',
  'terapia depresion ansiedad individual Argüelles',
  'terapia depresion ansiedad individual Moncloa',
  'terapia depresion ansiedad de pareja',
  'terapia depresion ansiedad de pareja Madrid',
  'terapia depresion ansiedad de pareja Chamberí',
  'terapia depresion ansiedad de pareja Argüelles',
  'terapia depresion ansiedad de pareja Moncloa',
  'terapia depresion ansiedad infantil',
  'terapia depresion ansiedad infantil Madrid',
  'terapia depresion ansiedad infantil Chamberí',
  'terapia depresion ansiedad infantil Argüelles',
  'terapia depresion ansiedad infantil Moncloa',
  'terapia depresion ansiedad online',
  'terapia depresion ansiedad online Madrid',
  'terapia depresion ansiedad online Chamberí',
  'terapia depresion ansiedad online Argüelles',
  'terapia depresion ansiedad online Moncloa',
  'depresion',
  'ansiedad',
  'depresion madrid',
  'depresion chamberí',
  'depresion argüelles',
  'depresion moncloa',
  'ansiedad madrid',
  'ansiedad chamberí',
  'ansiedad argüelles',
  'ansiedad moncloa',
] as const;

/** Lista completa para `Metadata.keywords` de la página de inicio. */
export function homeSearchKeywordsList(): string[] {
  return [
    ...clinicPrimaryKeywordsList(),
    ...clinicStripePaymentKeywordsList(),
    ...HOME_EXTENDED_SEARCH_KEYWORDS,
  ];
}

/**
 * Misma lista en un solo texto (schema.org `WebPage.keywords` suele ir como CSV).
 */
export function homeSearchKeywordsCsv(): string {
  return homeSearchKeywordsList().join(', ');
}
