"""crear tablas iniciales

Revision ID: 24eb0653259c
Revises: 
Create Date: 2026-04-07 16:22:29.635977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eb0653259c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dni_nie', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('motivo_consulta_inicial', sa.Text(), nullable=True),
    sa.Column('consentimiento_rgpd', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_dni_nie'), 'pacientes', ['dni_nie'], unique=True)
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=True)
    op.create_table('servicios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio_centimos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonos_pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('servicio_id', sa.String(length=36), nullable=False),
    sa.Column('sesiones_totales', sa.Integer(), nullable=False),
    sa.Column('sesiones_consumidas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('servicio_id', sa.String(length=36), nullable=False),
    sa.Column('inicio_iso', sa.DateTime(), nullable=False),
    sa.Column('fin_iso', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_sesiones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('cita_id', sa.String(length=36), nullable=False),
    sa.Column('notas_clinicas', sa.Text(), nullable=True),
    sa.Column('tareas_asignadas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('cita_id', sa.String(length=36), nullable=True),
    sa.Column('bono_id', sa.String(length=36), nullable=True),
    sa.Column('referencia_redsys', sa.String(length=100), nullable=True),
    sa.Column('importe_centimos', sa.Integer(), nullable=False),
    sa.Column('estado_transaccion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bono_id'], ['bonos_pacientes.id'], ),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia_redsys')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('historial_sesiones')
    op.drop_table('citas')
    op.drop_table('bonos_pacientes')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_dni_nie'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
