"""tabla auditoria

Revision ID: 2aab19ef83ee
Revises: 1377efb1f728
Create Date: 2026-04-07 18:12:52.364333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aab19ef83ee'
down_revision: Union[str, Sequence[str], None] = '1377efb1f728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.String(length=36), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    # ### end Alembic commands ###
