"""Initial_State

Revision ID: 301626726a8f
Revises: 
Create Date: 2026-04-11 15:29:23.875650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301626726a8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_ip_throttle',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('first_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_index(op.f('ix_auth_ip_throttle_blocked_until'), 'auth_ip_throttle', ['blocked_until'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dni_nie', sa.String(length=255), nullable=False),
    sa.Column('dni_nie_bidx', sa.String(length=64), nullable=True),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo_bidx', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=255), nullable=True),
    sa.Column('telefono_bidx', sa.String(length=64), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('motivo_consulta_inicial', sa.Text(), nullable=True),
    sa.Column('experiencia_terapia', sa.String(length=255), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('consentimiento_rgpd', sa.Boolean(), nullable=False),
    sa.Column('firma_rgpd_path', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_dni_nie_bidx'), 'pacientes', ['dni_nie_bidx'], unique=True)
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=True)
    op.create_index(op.f('ix_pacientes_nombre_completo_bidx'), 'pacientes', ['nombre_completo_bidx'], unique=False)
    op.create_index(op.f('ix_pacientes_telefono_bidx'), 'pacientes', ['telefono_bidx'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('precio_centimos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.String(length=36), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonos_pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('servicio_id', sa.String(length=36), nullable=False),
    sa.Column('sesiones_totales', sa.Integer(), nullable=False),
    sa.Column('sesiones_consumidas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('servicio_id', sa.String(length=36), nullable=False),
    sa.Column('inicio_iso', sa.DateTime(), nullable=False),
    sa.Column('fin_iso', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('body_ciphertext', sa.Text(), nullable=False),
    sa.Column('encryption_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_conversation_id'), 'mensajes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_mensajes_sender_user_id'), 'mensajes', ['sender_user_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_user_id'), 'otp_challenges', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_first', sa.String(length=45), nullable=False),
    sa.Column('ip_last', sa.String(length=45), nullable=False),
    sa.Column('ip_network', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('admin_ip_lock', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_device_fingerprint_hash'), 'user_sessions', ['device_fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_mfa_verified_at'), 'user_sessions', ['mfa_verified_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_revoked_at'), 'user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('historial_sesiones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('cita_id', sa.String(length=36), nullable=False),
    sa.Column('notas_clinicas', sa.Text(), nullable=True),
    sa.Column('tareas_asignadas', sa.Text(), nullable=True),
    sa.Column('estado_emocional', sa.String(length=50), nullable=True),
    sa.Column('nivel_cortisol_estimado', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('cita_id', sa.String(length=36), nullable=True),
    sa.Column('bono_id', sa.String(length=36), nullable=True),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('referencia_redsys', sa.String(length=100), nullable=True),
    sa.Column('importe_centimos', sa.Integer(), nullable=False),
    sa.Column('estado_transaccion', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bono_id'], ['bonos_pacientes.id'], ),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia_redsys')
    )
    op.create_index(op.f('ix_pagos_stripe_event_id'), 'pagos', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_stripe_event_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_table('historial_sesiones')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_revoked_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_mfa_verified_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_fingerprint_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_otp_challenges_user_id'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_mensajes_sender_user_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_conversation_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_table('citas')
    op.drop_table('bonos_pacientes')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_pacientes_telefono_bidx'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nombre_completo_bidx'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_dni_nie_bidx'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_auth_ip_throttle_blocked_until'), table_name='auth_ip_throttle')
    op.drop_table('auth_ip_throttle')
    # ### end Alembic commands ###
