"""actualizacion_elite_modelos

Revision ID: 4b0730df719f
Revises: 2aab19ef83ee
Create Date: 2026-04-07 18:19:43.879801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0730df719f'
down_revision: Union[str, Sequence[str], None] = '2aab19ef83ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial_sesiones', sa.Column('estado_emocional', sa.String(length=50), nullable=True))
    op.add_column('historial_sesiones', sa.Column('nivel_cortisol_estimado', sa.Integer(), nullable=True))
    op.add_column('historial_sesiones', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.add_column('pacientes', sa.Column('firma_rgpd_path', sa.String(length=255), nullable=True))
    op.add_column('pagos', sa.Column('fecha_pago', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'fecha_pago')
    op.drop_column('pacientes', 'firma_rgpd_path')
    op.drop_column('historial_sesiones', 'fecha_registro')
    op.drop_column('historial_sesiones', 'nivel_cortisol_estimado')
    op.drop_column('historial_sesiones', 'estado_emocional')
    # ### end Alembic commands ###
