"""anadir soft delete

Revision ID: 61f21f52304b
Revises: feb649b0f69b
Create Date: 2026-04-07 17:12:02.965159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f21f52304b'
down_revision: Union[str, Sequence[str], None] = 'feb649b0f69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonos_pacientes', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('citas', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('historial_sesiones', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('pacientes', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('pagos', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('servicios', sa.Column('activo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicios', 'activo')
    op.drop_column('pagos', 'activo')
    op.drop_column('pacientes', 'activo')
    op.drop_column('historial_sesiones', 'activo')
    op.drop_column('citas', 'activo')
    op.drop_column('bonos_pacientes', 'activo')
    # ### end Alembic commands ###
