// AUTO-GENERATED by scripts/bundle_for_deploy.mjs
// Do not edit directly — edit the source files and rerun the script.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

// ---- inlined from _shared/cors.ts ----
// Cabeceras CORS compartidas por todas las Edge Functions
// Restringido al origen de producción + localhost dev
const ALLOWED_ORIGINS = [
  "http://localhost:3000",
  "https://clinica-almudena.vercel.app",
  Deno.env.get("FRONTEND_URL") ?? "",
].filter(Boolean);

function buildCorsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}

function handleOptions(req: Request): Response | null {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: buildCorsHeaders(req.headers.get("origin")),
    });
  }
  return null;
}


// ---- inlined from _shared/stripe.ts ----
// Cliente Stripe minimalista (REST API directa, sin SDK).
// Evitamos el SDK oficial para minimizar cold-start y superficie de dependencias.

const STRIPE_API = "https://api.stripe.com/v1";

interface StripeError { error?: { message?: string; code?: string; type?: string } }

class StripeApiError extends Error {
  public code: string | undefined;
  public status: number;
  constructor(status: number, message: string, code?: string) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

function apiKey(): string {
  const k = Deno.env.get("STRIPE_SECRET_KEY");
  if (!k) throw new StripeApiError(500, "STRIPE_SECRET_KEY no configurado");
  return k;
}

function encodeForm(obj: Record<string, unknown>, prefix = ""): string {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;
    const k = prefix ? `${prefix}[${key}]` : key;
    if (Array.isArray(value)) {
      value.forEach((v, i) => {
        if (typeof v === "object" && v !== null) {
          parts.push(encodeForm(v as Record<string, unknown>, `${k}[${i}]`));
        } else {
          parts.push(`${encodeURIComponent(`${k}[${i}]`)}=${encodeURIComponent(String(v))}`);
        }
      });
    } else if (typeof value === "object") {
      parts.push(encodeForm(value as Record<string, unknown>, k));
    } else {
      parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(value))}`);
    }
  }
  return parts.filter(Boolean).join("&");
}

async function stripeRequest<T>(
  path: string,
  method: "GET" | "POST",
  body?: Record<string, unknown>,
  idempotencyKey?: string,
): Promise<T> {
  const headers: Record<string, string> = {
    Authorization: `Bearer ${apiKey()}`,
  };
  if (method === "POST") {
    headers["Content-Type"] = "application/x-www-form-urlencoded";
  }
  if (idempotencyKey) {
    headers["Idempotency-Key"] = idempotencyKey;
  }

  const res = await fetch(`${STRIPE_API}${path}`, {
    method,
    headers,
    body: body ? encodeForm(body) : undefined,
  });

  if (!res.ok) {
    const err = (await res.json().catch(() => ({}))) as StripeError;
    throw new StripeApiError(
      res.status,
      err.error?.message ?? `stripe ${res.status}`,
      err.error?.code,
    );
  }

  return (await res.json()) as T;
}

// ---------------------------------------------------------------------------
// Checkout Sessions
// ---------------------------------------------------------------------------

interface CheckoutLineItem {
  name: string;
  description?: string;
  amount_centimos: number;
  quantity?: number;
}

interface CreateCheckoutInput {
  customer_email: string;
  success_url: string;
  cancel_url: string;
  client_reference_id?: string;
  metadata: Record<string, string>;
  line_items: CheckoutLineItem[];
  idempotency_key: string;
  payment_method_types?: string[];
  locale?: string;
}

interface CheckoutSession {
  id: string;
  url: string;
  payment_intent: string | null;
  customer: string | null;
  payment_status: string;
  amount_total: number;
  currency: string;
  metadata?: Record<string, string>;
}

async function createCheckoutSession(
  input: CreateCheckoutInput,
): Promise<CheckoutSession> {
  const body: Record<string, unknown> = {
    mode: "payment",
    customer_email: input.customer_email,
    success_url: input.success_url,
    cancel_url: input.cancel_url,
    client_reference_id: input.client_reference_id,
    locale: input.locale ?? "es",
    payment_method_types: input.payment_method_types ?? ["card"],
    metadata: input.metadata,
    line_items: input.line_items.map((it) => ({
      price_data: {
        currency: "eur",
        unit_amount: it.amount_centimos,
        product_data: {
          name: it.name,
          description: it.description ?? undefined,
        },
      },
      quantity: it.quantity ?? 1,
    })),
    "payment_intent_data[metadata]": undefined, // placeholder
  };

  // metadata tambien dentro del PaymentIntent (para que el webhook lo tenga
  // accesible tanto si escuchamos checkout.session.completed como payment_intent.succeeded)
  for (const [k, v] of Object.entries(input.metadata)) {
    body[`payment_intent_data[metadata][${k}]`] = v;
  }

  return await stripeRequest<CheckoutSession>(
    "/checkout/sessions",
    "POST",
    body,
    input.idempotency_key,
  );
}

// ---------------------------------------------------------------------------
// Refunds
// ---------------------------------------------------------------------------

interface CreateRefundInput {
  payment_intent: string;
  amount_centimos?: number;        // null = refund total
  reason?: "duplicate" | "fraudulent" | "requested_by_customer";
  idempotency_key: string;
  metadata?: Record<string, string>;
}

interface StripeRefund {
  id: string;
  amount: number;
  currency: string;
  status: string;          // 'succeeded' | 'pending' | 'failed' | 'requires_action'
  payment_intent: string;
  reason?: string | null;
}

async function createRefund(input: CreateRefundInput): Promise<StripeRefund> {
  const body: Record<string, unknown> = {
    payment_intent: input.payment_intent,
    reason: input.reason ?? "requested_by_customer",
  };
  if (typeof input.amount_centimos === "number" && input.amount_centimos > 0) {
    body.amount = input.amount_centimos;
  }
  if (input.metadata) {
    for (const [k, v] of Object.entries(input.metadata)) {
      body[`metadata[${k}]`] = v;
    }
  }
  return await stripeRequest<StripeRefund>("/refunds", "POST", body, input.idempotency_key);
}

// ---------------------------------------------------------------------------
// Webhook signature verification (Stripe spec)
// ---------------------------------------------------------------------------

interface ParsedSignatureHeader {
  timestamp: number;
  signatures: string[];
}

function parseSignatureHeader(header: string): ParsedSignatureHeader | null {
  const parts = header.split(",").map((s) => s.trim());
  let timestamp = 0;
  const signatures: string[] = [];
  for (const p of parts) {
    const [k, v] = p.split("=");
    if (!k || !v) continue;
    if (k === "t") timestamp = Number(v);
    else if (k === "v1") signatures.push(v);
  }
  if (!timestamp || signatures.length === 0) return null;
  return { timestamp, signatures };
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

/**
 * Verifica la firma del webhook según la especificación oficial de Stripe.
 * Tolerancia de 5 minutos para prevenir replay attacks.
 * @returns el evento parseado si es válido, o null si no lo es.
 */
async function verifyWebhookSignature(
  rawBody: string,
  sigHeader: string | null,
  secret: string,
  toleranceSeconds = 300,
): Promise<unknown | null> {
  if (!sigHeader) return null;
  const parsed = parseSignatureHeader(sigHeader);
  if (!parsed) return null;

  const now = Math.floor(Date.now() / 1000);
  if (Math.abs(now - parsed.timestamp) > toleranceSeconds) return null;

  const payload = `${parsed.timestamp}.${rawBody}`;

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(payload),
  );
  const expectedHex = bytesToHex(new Uint8Array(signature));

  const match = parsed.signatures.some((s) => timingSafeEqual(s, expectedHex));
  if (!match) return null;

  try {
    return JSON.parse(rawBody);
  } catch {
    return null;
  }
}


// ---- main function body ----
// Edge Function: stripe-webhook
// -----------------------------------------------------------------------------
// Recibe eventos de Stripe (sin JWT porque Stripe no manda uno), verifica la
// firma HMAC-SHA256 con STRIPE_WEBHOOK_SECRET, y procesa los eventos soportados:
//   * checkout.session.completed       → confirma cita o crea bono
//   * checkout.session.async_payment_succeeded  (SEPA) → idem
//   * payment_intent.payment_failed    → marca pago fallido
//
// Idempotencia: pagos.stripe_event_id UNIQUE + tabla stripe_events.
// Toda la mutación va vía RPC SECURITY DEFINER procesar_pago_stripe.
// -----------------------------------------------------------------------------

// deno-lint-ignore-file no-explicit-any


interface StripeEvent {
  id: string;
  type: string;
  api_version?: string;
  livemode?: boolean;
  data: { object: any };
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

const FRONTEND_URL = Deno.env.get("FRONTEND_URL") ?? "https://clinica-almudena.vercel.app";

Deno.serve(async (req) => {
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const webhookSecret = Deno.env.get("STRIPE_WEBHOOK_SECRET");
  if (!webhookSecret) return json({ error: "webhook_secret_not_configured" }, 500);

  // IMPORTANTE: leer el body como TEXTO RAW. La firma se calcula sobre el
  // payload byte-a-byte; cualquier reparseo lo invalidaría.
  const rawBody = await req.text();
  const sigHeader = req.headers.get("stripe-signature");

  const event = (await verifyWebhookSignature(rawBody, sigHeader, webhookSecret)) as
    | StripeEvent
    | null;

  if (!event) {
    return json({ error: "invalid_signature" }, 400);
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const admin = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });

  // Audit del evento (upsert para idempotencia si Stripe reintenta)
  await admin
    .from("stripe_events")
    .upsert(
      {
        id: event.id,
        type: event.type,
        api_version: event.api_version ?? null,
        livemode: Boolean(event.livemode),
        payload: event as unknown as Record<string, unknown>,
      },
      { onConflict: "id" },
    );

  try {
    if (
      event.type === "checkout.session.completed" ||
      event.type === "checkout.session.async_payment_succeeded"
    ) {
      await handleCheckoutCompleted(admin, event);
    } else if (event.type === "payment_intent.payment_failed") {
      await handlePaymentFailed(admin, event);
    }
    // Cualquier otro tipo queda logueado en stripe_events y devolvemos 200.

    await admin
      .from("stripe_events")
      .update({ processed_at: new Date().toISOString() })
      .eq("id", event.id);

    return json({ ok: true, type: event.type }, 200);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    await admin
      .from("stripe_events")
      .update({ processing_error: msg })
      .eq("id", event.id);

    // Stripe reintentará si devolvemos 5xx (hasta 72h con backoff).
    return json({ error: "processing_error", detail: msg }, 500);
  }
});

async function handleCheckoutCompleted(
  admin: ReturnType<typeof createClient>,
  event: StripeEvent,
): Promise<void> {
  const session = event.data.object;
  if (session.payment_status !== "paid") {
    // async_payment_succeeded llega con paid; en otros casos ignoramos.
    return;
  }

  const metadata = (session.metadata ?? {}) as Record<string, string>;
  const kind = metadata.kind;
  const userId = metadata.user_id;

  if (!userId || (kind !== "cita" && kind !== "bono")) {
    throw new Error(`metadata inválido: kind=${kind} user_id=${userId}`);
  }

  // Obtener método de pago del PaymentIntent (las Sessions solo tienen payment_intent id)
  let metodo: string | null = null;
  const paymentIntentId: string | null = session.payment_intent ?? null;
  if (paymentIntentId) {
    const piRes = await fetch(
      `https://api.stripe.com/v1/payment_intents/${paymentIntentId}`,
      { headers: { Authorization: `Bearer ${Deno.env.get("STRIPE_SECRET_KEY")}` } },
    );
    if (piRes.ok) {
      const pi = await piRes.json();
      metodo = pi?.charges?.data?.[0]?.payment_method_details?.type ?? pi?.payment_method_types?.[0] ?? null;
    }
  }

  const { data, error } = await admin.rpc("procesar_pago_stripe", {
    p_stripe_event_id:       event.id,
    p_stripe_session_id:     session.id,
    p_stripe_payment_intent: paymentIntentId,
    p_stripe_customer_id:    session.customer ?? null,
    p_user_id:               userId,
    p_cita_id:               kind === "cita" ? (metadata.cita_id ?? null) : null,
    p_bono_config_id:        kind === "bono" ? (metadata.bono_config_id ?? null) : null,
    p_importe_centimos:      session.amount_total ?? 0,
    p_moneda:                (session.currency ?? "eur").toUpperCase(),
    p_metodo:                metodo,
    p_metadata:              metadata,
  });

  if (error) throw new Error(`procesar_pago_stripe: ${error.message}`);

  const result = (Array.isArray(data) ? data[0] : data) as {
    pago_id: string;
    cita_confirmada: boolean;
    bono_creado: boolean;
    bono_id: string | null;
    ya_procesado: boolean;
  } | null;

  if (!result || result.ya_procesado) return;

  // Disparar email de confirmación (fire-and-forget, no bloqueamos el webhook)
  if (kind === "cita" && result.cita_confirmada && metadata.cita_id) {
    await triggerBookingEmail(userId, metadata.cita_id);
  }
}

async function handlePaymentFailed(
  admin: ReturnType<typeof createClient>,
  event: StripeEvent,
): Promise<void> {
  const pi = event.data.object;
  const piId: string | undefined = pi?.id;
  if (!piId) return;

  await admin
    .from("pagos")
    .update({ estado: "fallido", updated_at: new Date().toISOString() })
    .eq("stripe_payment_intent", piId);
}

async function triggerBookingEmail(userId: string, citaId: string): Promise<void> {
  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const admin = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });

    const { data } = await admin
      .from("citas")
      .select(`inicio, servicio:servicios!inner(nombre, duracion_minutos)`)
      .eq("id", citaId)
      .maybeSingle();

    if (!data) return;

    const servicio = Array.isArray((data as any).servicio) ? (data as any).servicio[0] : (data as any).servicio;
    if (!servicio) return;

    await fetch(`${supabaseUrl}/functions/v1/send-email`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${serviceKey}`,
      },
      body: JSON.stringify({
        type: "booking_confirmed",
        to_user_id: userId,
        cita_id: citaId,
        data: {
          servicio: servicio.nombre,
          inicio: (data as any).inicio,
          duracion_min: servicio.duracion_minutos,
        },
      }),
    });
  } catch {
    // Mejor-esfuerzo. El pago ya quedó registrado.
  }
}
