// AUTO-GENERATED by supabase/scripts/bundle_for_deploy.mjs
// Do not edit directly - edit the source files and rerun the script.

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

// ---- inlined from _shared/cors.ts ----
// Cabeceras CORS compartidas por todas las Edge Functions
// Restringido al origen de producción + localhost dev
const ALLOWED_ORIGINS = [
  "http://localhost:3000",
  "https://clinica-almudena.vercel.app",
  "https://amclinicapsicologia.es",
  "https://www.amclinicapsicologia.es",
  Deno.env.get("FRONTEND_URL") ?? "",
].filter(Boolean);

function buildCorsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}

function handleOptions(req: Request): Response | null {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      status: 204,
      headers: buildCorsHeaders(req.headers.get("origin")),
    });
  }
  return null;
}


// ---- inlined from _shared/resend.ts ----
// Cliente Resend minimalista con retry exponencial.
// No usamos el SDK oficial porque añade 80kB innecesarios; la API REST
// es trivial (un único POST /emails).

interface ResendPayload {
  from: string;
  to: string | string[];
  subject: string;
  html: string;
  text?: string;
  reply_to?: string;
  tags?: Array<{ name: string; value: string }>;
}

interface ResendOkResponse { id: string }
interface ResendErrResponse { name: string; message: string; statusCode?: number }

interface SendResult {
  ok: boolean;
  providerId?: string;
  error?: string;
  attempts: number;
}

const RESEND_ENDPOINT = "https://api.resend.com/emails";
const MAX_ATTEMPTS = 3;
const BASE_DELAY_MS = 400; // 400ms → 800ms → 1600ms

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function sendViaResend(payload: ResendPayload): Promise<SendResult> {
  const apiKey = Deno.env.get("RESEND_API_KEY");
  if (!apiKey) {
    return { ok: false, error: "RESEND_API_KEY no configurado", attempts: 0 };
  }

  let lastError = "unknown error";
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const res = await fetch(RESEND_ENDPOINT, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (res.ok) {
        const data = (await res.json()) as ResendOkResponse;
        return { ok: true, providerId: data.id, attempts: attempt };
      }

      const err = (await res.json().catch(() => ({}))) as ResendErrResponse;
      lastError = `${res.status} ${err.message ?? err.name ?? res.statusText}`;

      // 4xx (excepto 429) → no reintentar, error de payload / auth
      if (res.status >= 400 && res.status < 500 && res.status !== 429) {
        return { ok: false, error: lastError, attempts: attempt };
      }
    } catch (e) {
      lastError = e instanceof Error ? e.message : String(e);
    }

    if (attempt < MAX_ATTEMPTS) {
      await sleep(BASE_DELAY_MS * 2 ** (attempt - 1));
    }
  }

  return { ok: false, error: lastError, attempts: MAX_ATTEMPTS };
}


// ---- inlined from _shared/templates.ts ----
// Plantillas HTML transaccionales inline-styled (email clients no soportan CSS extern)
// Paleta alineada con "Serenity Moncloa" de la web pública.
// Tipografía: system stack (Georgia/serif + Helvetica/sans) — máxima compatibilidad.

const COLORS = {
  parchment: "#F3E9DD",
  ink:       "#1E1B18",
  inkSoft:   "#4A4640",
  sage:      "#6B8A7A",
  sageDark:  "#4F6B5C",
  warm:      "#C99463",
  hairline:  "rgba(30,27,24,0.12)",
} as const;

function escapeHtml(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return "";
  return String(v)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatDateEs(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("es-ES", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "Europe/Madrid",
  }).format(d);
}

function formatTimeEs(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("es-ES", {
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "Europe/Madrid",
  }).format(d);
}

interface ShellOptions {
  preheader: string;
  appUrl: string;
}

function shell(inner: string, { preheader, appUrl }: ShellOptions): string {
  const safePreheader = escapeHtml(preheader);
  return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="light" />
<meta name="supported-color-schemes" content="light" />
<title>Clínica Almudena Marchesi</title>
</head>
<body style="margin:0;padding:0;background-color:${COLORS.parchment};font-family:Georgia,'Times New Roman',serif;color:${COLORS.ink};-webkit-font-smoothing:antialiased;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;">${safePreheader}</div>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background-color:${COLORS.parchment};padding:32px 16px;">
    <tr><td align="center">
      <table role="presentation" width="560" cellspacing="0" cellpadding="0" border="0" style="max-width:560px;width:100%;background-color:#FBF6EF;border:1px solid ${COLORS.hairline};border-radius:20px;overflow:hidden;">
        <tr><td style="padding:32px 40px 20px 40px;border-bottom:1px solid ${COLORS.hairline};">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
            <tr>
              <td style="vertical-align:middle;">
                <span style="display:inline-block;width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,${COLORS.sage} 0%,${COLORS.sageDark} 100%);vertical-align:middle;"></span>
                <span style="display:inline-block;margin-left:12px;vertical-align:middle;font-family:Georgia,serif;font-size:18px;letter-spacing:0.02em;color:${COLORS.ink};">Almudena Marchesi Fernández</span>
              </td>
            </tr>
          </table>
        </td></tr>
        <tr><td style="padding:32px 40px 40px 40px;font-size:16px;line-height:1.65;color:${COLORS.ink};">
          ${inner}
        </td></tr>
        <tr><td style="padding:24px 40px 32px 40px;border-top:1px solid ${COLORS.hairline};font-family:Helvetica,Arial,sans-serif;font-size:12px;line-height:1.6;color:${COLORS.inkSoft};">
          <p style="margin:0 0 6px 0;">Clínica Almudena Marchesi Fernández · Colegiada nº M-30815</p>
          <p style="margin:0 0 6px 0;">Calle de Moncloa, Madrid · <a href="tel:+34600000000" style="color:${COLORS.inkSoft};text-decoration:none;">+34 600 000 000</a></p>
          <p style="margin:0;">Has recibido este correo porque eres paciente de la consulta. <a href="${appUrl}/portal/ajustes" style="color:${COLORS.sageDark};">Gestionar notificaciones</a></p>
        </td></tr>
      </table>
      <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:11px;color:${COLORS.inkSoft};">© ${new Date().getFullYear()} Clínica Almudena Marchesi Fernández</p>
    </td></tr>
  </table>
</body>
</html>`;
}

function button(label: string, href: string): string {
  return `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0;">
    <tr><td style="border-radius:999px;background-color:${COLORS.sageDark};">
      <a href="${escapeHtml(href)}" style="display:inline-block;padding:14px 28px;font-family:Helvetica,Arial,sans-serif;font-size:14px;letter-spacing:0.04em;text-transform:uppercase;color:#FBF6EF;text-decoration:none;border-radius:999px;">${escapeHtml(label)}</a>
    </td></tr>
  </table>`;
}

function h1(text: string): string {
  return `<h1 style="margin:0 0 16px 0;font-family:Georgia,serif;font-size:28px;line-height:1.2;font-weight:400;color:${COLORS.ink};">${escapeHtml(text)}</h1>`;
}

function eyebrow(text: string): string {
  return `<p style="margin:0 0 12px 0;font-family:Helvetica,Arial,sans-serif;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:${COLORS.sageDark};">${escapeHtml(text)}</p>`;
}

function detailRow(label: string, value: string): string {
  return `<tr>
    <td style="padding:10px 0;border-bottom:1px solid ${COLORS.hairline};font-family:Helvetica,Arial,sans-serif;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:${COLORS.inkSoft};width:40%;">${escapeHtml(label)}</td>
    <td style="padding:10px 0;border-bottom:1px solid ${COLORS.hairline};font-family:Georgia,serif;font-size:15px;color:${COLORS.ink};text-align:right;">${escapeHtml(value)}</td>
  </tr>`;
}

// ---------------------------------------------------------------------------
// Templates exportados
// ---------------------------------------------------------------------------

interface WelcomeData {
  display_name?: string | null;
  app_url: string;
}

function renderWelcome(data: WelcomeData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const greeting = name ? `Bienvenida, ${name}` : "Bienvenida a tu espacio";
  const html = shell(
    `${eyebrow("Acceso al portal")}
     ${h1(greeting)}
     <p style="margin:0 0 16px 0;">Tu cuenta en la Clínica Almudena Marchesi Fernández ya está activa. Desde el portal podrás consultar tus próximas citas, reservar nuevas sesiones, acceder a recursos personalizados y hablar directamente con Almudena.</p>
     ${button("Abrir mi portal", `${data.app_url}/portal`)}
     <p style="margin:0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">Si no esperabas este correo, puedes ignorarlo sin problema.</p>`,
    { preheader: "Tu portal de paciente está listo.", appUrl: data.app_url },
  );
  const text = `${greeting}\n\nTu cuenta en la Clínica Almudena Marchesi Fernández está activa.\nAccede al portal: ${data.app_url}/portal\n\nSi no esperabas este correo, ignóralo.`;
  return { subject: "Bienvenida a tu portal", html, text };
}

interface BookingConfirmedData {
  display_name?: string | null;
  servicio: string;
  inicio: string;   // ISO
  duracion_min: number;
  app_url: string;
}

function renderBookingConfirmed(data: BookingConfirmedData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const fecha = formatDateEs(data.inicio);
  const hora  = formatTimeEs(data.inicio);
  const html = shell(
    `${eyebrow("Reserva confirmada")}
     ${h1(name ? `Nos vemos pronto, ${name}` : "Tu sesión está confirmada")}
     <p style="margin:0 0 20px 0;">Hemos reservado tu sesión. Aquí tienes los detalles:</p>
     <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 8px 0;">
       ${detailRow("Servicio", data.servicio)}
       ${detailRow("Fecha", fecha)}
       ${detailRow("Hora", `${hora} (${data.duracion_min} min)`)}
     </table>
     ${button("Ver mis citas", `${data.app_url}/portal/citas`)}
     <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">¿Necesitas cambiar la fecha? Puedes hacerlo desde el portal con al menos 24h de antelación.</p>`,
    { preheader: `${data.servicio} · ${fecha} · ${hora}`, appUrl: data.app_url },
  );
  const text = `Reserva confirmada\n\n${data.servicio}\n${fecha} a las ${hora} (${data.duracion_min} min)\n\nGestionar citas: ${data.app_url}/portal/citas`;
  return { subject: `Confirmación: ${data.servicio} · ${fecha}`, html, text };
}

interface Reminder24hData {
  display_name?: string | null;
  servicio: string;
  inicio: string;
  duracion_min: number;
  app_url: string;
}

function renderReminder24h(data: Reminder24hData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const fecha = formatDateEs(data.inicio);
  const hora  = formatTimeEs(data.inicio);
  const html = shell(
    `${eyebrow("Recordatorio 24 horas")}
     ${h1(name ? `Te espero mañana, ${name}` : "Tu sesión es mañana")}
     <p style="margin:0 0 20px 0;">Te escribo para recordarte tu sesión de mañana. Si necesitas reprogramarla, avísame lo antes posible.</p>
     <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 8px 0;">
       ${detailRow("Servicio", data.servicio)}
       ${detailRow("Fecha", fecha)}
       ${detailRow("Hora", `${hora} (${data.duracion_min} min)`)}
     </table>
     ${button("Ver detalle en el portal", `${data.app_url}/portal/citas`)}
     <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">Recuerda llegar unos minutos antes. Un fuerte abrazo.</p>`,
    { preheader: `Mañana a las ${hora} · ${data.servicio}`, appUrl: data.app_url },
  );
  const text = `Recordatorio: mañana tienes sesión.\n\n${data.servicio}\n${fecha} a las ${hora} (${data.duracion_min} min)\n\nVer detalle: ${data.app_url}/portal/citas`;
  return { subject: `Recordatorio: tu sesión de mañana a las ${hora}`, html, text };
}

interface BookingCancelledData {
  display_name?: string | null;
  servicio: string;
  inicio: string;
  app_url: string;
}

function renderBookingCancelled(data: BookingCancelledData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const fecha = formatDateEs(data.inicio);
  const hora  = formatTimeEs(data.inicio);
  const html = shell(
    `${eyebrow("Cita cancelada")}
     ${h1(name ? `Cita cancelada, ${name}` : "Tu cita ha sido cancelada")}
     <p style="margin:0 0 20px 0;">Queda confirmada la cancelación de tu sesión:</p>
     <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 8px 0;">
       ${detailRow("Servicio", data.servicio)}
       ${detailRow("Fecha prevista", `${fecha} · ${hora}`)}
     </table>
     ${button("Reservar otra sesión", `${data.app_url}/portal/citas/reservar`)}
     <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">Si la cancelación es un error, contacta con la consulta cuanto antes.</p>`,
    { preheader: `Cancelación ${fecha} · ${hora}`, appUrl: data.app_url },
  );
  const text = `Cita cancelada.\n\n${data.servicio}\n${fecha} a las ${hora}\n\nReservar de nuevo: ${data.app_url}/portal/citas/reservar`;
  return { subject: `Cancelación: ${data.servicio} · ${fecha}`, html, text };
}

interface NuevaAsignacionData {
  display_name?: string | null;
  titulo_recurso: string;
  tipo_recurso: string;  // 'pdf' | 'video' | ...
  app_url: string;
}

function renderNuevaAsignacion(data: NuevaAsignacionData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const html = shell(
    `${eyebrow("Nuevo recurso")}
     ${h1(name ? `Almudena te ha compartido algo, ${name}` : "Tienes un nuevo recurso asignado")}
     <p style="margin:0 0 12px 0;">Se ha añadido a tu portal:</p>
     <p style="margin:0 0 20px 0;font-family:Georgia,serif;font-size:18px;color:${COLORS.ink};"><strong>${escapeHtml(data.titulo_recurso)}</strong> <span style="font-family:Helvetica,Arial,sans-serif;font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:${COLORS.sageDark};">· ${escapeHtml(data.tipo_recurso)}</span></p>
     ${button("Ver en el portal", `${data.app_url}/portal/recursos`)}`,
    { preheader: `Nuevo recurso: ${data.titulo_recurso}`, appUrl: data.app_url },
  );
  const text = `Nuevo recurso asignado: ${data.titulo_recurso} (${data.tipo_recurso})\n\nVer en el portal: ${data.app_url}/portal/recursos`;
  return { subject: `Nuevo recurso: ${data.titulo_recurso}`, html, text };
}

// ---------------------------------------------------------------------------
// RGPD — acuse de recibo + exportación lista
// ---------------------------------------------------------------------------

const TIPO_LABELS: Record<string, string> = {
  exportar: "exportación de datos",
  borrado: "supresión (baja de cuenta)",
  rectificar: "rectificación",
  oposicion: "oposición al tratamiento",
  portabilidad: "portabilidad",
  limitacion: "limitación del tratamiento",
};

interface RgpdAckData {
  display_name?: string | null;
  tipo: string;
  fecha_limite: string | null;
  app_url: string;
}

function renderRgpdAck(data: RgpdAckData): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const tipoLabel = TIPO_LABELS[data.tipo] ?? "solicitud RGPD";
  const plazo = data.fecha_limite
    ? formatDateEs(data.fecha_limite)
    : "30 días naturales";
  const html = shell(
    `${eyebrow("Solicitud RGPD recibida")}
     ${h1(name ? `Hemos recibido tu solicitud, ${name}` : "Solicitud RGPD recibida")}
     <p style="margin:0 0 16px 0;">Tu solicitud de <strong>${escapeHtml(tipoLabel)}</strong> está registrada. Almudena te responderá en un plazo máximo de <strong>${escapeHtml(plazo)}</strong>, conforme al art. 12 del RGPD.</p>
     <p style="margin:0 0 16px 0;">Puedes consultar el estado desde tu portal en cualquier momento.</p>
     ${button("Ver estado", `${data.app_url}/portal/ajustes`)}
     <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">Si la solicitud fue un error, contacta con nosotros respondiendo a este correo.</p>`,
    { preheader: `Solicitud de ${tipoLabel} registrada`, appUrl: data.app_url },
  );
  const text = `Solicitud RGPD recibida: ${tipoLabel}\nPlazo de respuesta: ${plazo}\n\nVer estado: ${data.app_url}/portal/ajustes`;
  return { subject: `Tu solicitud RGPD de ${tipoLabel}`, html, text };
}

interface RgpdExportReadyData {
  display_name?: string | null;
  signed_url: string;
  expires_at: string;
  app_url: string;
}

function renderRgpdExportReady(
  data: RgpdExportReadyData
): { subject: string; html: string; text: string } {
  const name = data.display_name?.split(" ")[0] ?? "";
  const expira = formatDateEs(data.expires_at);
  const html = shell(
    `${eyebrow("Exportación lista")}
     ${h1(name ? `Tu copia está lista, ${name}` : "Tu copia de datos está lista")}
     <p style="margin:0 0 16px 0;">Hemos preparado un archivo con todos tus datos personales, citas, pagos, mensajes y adjuntos. El enlace caduca el <strong>${escapeHtml(expira)}</strong> por seguridad.</p>
     ${button("Descargar mi copia", data.signed_url)}
     <p style="margin:16px 0 0 0;font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${COLORS.inkSoft};">Si el enlace caduca, puedes solicitar una nueva exportación desde tu portal en cualquier momento.</p>`,
    { preheader: "Tu exportación RGPD está lista.", appUrl: data.app_url },
  );
  const text = `Tu copia de datos está lista.\nEnlace (caduca ${expira}): ${data.signed_url}\n\nSi caduca, puedes solicitar otra desde ${data.app_url}/portal/ajustes`;
  return { subject: "Tu copia de datos RGPD está lista", html, text };
}


// ---- main function body ----
// Edge Function: send-email
// -----------------------------------------------------------------------------
// Router de emails transaccionales. Recibe { type, to_user_id, data } y:
//   1. Valida JWT del caller (service_role o usuario autenticado).
//   2. Verifica opt-in del paciente en notificaciones_prefs (RLS-bypassed).
//   3. Inserta fila `pending` en emails_log (UNIQUE dedupe nos protege).
//   4. Renderiza HTML + text desde _shared/templates.
//   5. Envía vía Resend con retry exponencial (3 intentos).
//   6. Actualiza emails_log a 'sent' / 'failed' con provider_id o error.
// -----------------------------------------------------------------------------

// deno-lint-ignore-file no-explicit-any
import {
  renderWelcome,
  renderBookingConfirmed,
  renderReminder24h,
  renderBookingCancelled,
  renderNuevaAsignacion,
} from "../_shared/templates.ts";

type EmailType =
  | "welcome"
  | "booking_confirmed"
  | "reminder_24h"
  | "booking_cancelled"
  | "nueva_asignacion";

interface SendEmailRequest {
  type: EmailType;
  to_user_id?: string;    // preferente — resuelve email desde profiles
  to_email?: string;      // fallback si to_user_id no disponible
  cita_id?: string;
  data?: Record<string, unknown>;
}

interface ProfileRow {
  id: string;
  email: string;
  display_name: string | null;
}

interface PrefsRow {
  welcome: boolean;
  booking_confirmed: boolean;
  booking_cancelled: boolean;
  reminder_24h: boolean;
  nueva_asignacion: boolean;
}

const APP_URL = Deno.env.get("FRONTEND_URL") ?? "https://amclinicapsicologia.es";
const FROM_EMAIL = Deno.env.get("RESEND_FROM_EMAIL") ?? "Clínica Almudena <onboarding@resend.dev>";
const REPLY_TO = Deno.env.get("RESEND_REPLY_TO") ?? undefined;

function json(body: unknown, status: number, corsHeaders: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function supabaseAdmin(): SupabaseClient {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) throw new Error("SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY no configurados");
  return createClient(url, key, { auth: { persistSession: false } });
}

function prefsOptInForType(prefs: PrefsRow | null, type: EmailType): boolean {
  if (!prefs) return true;
  return Boolean(prefs[type]);
}

function renderFor(type: EmailType, data: Record<string, unknown>, profile: ProfileRow | null) {
  const base = { display_name: profile?.display_name ?? null, app_url: APP_URL };
  switch (type) {
    case "welcome":
      return renderWelcome({ ...base });
    case "booking_confirmed":
      return renderBookingConfirmed({
        ...base,
        servicio:      String(data.servicio ?? ""),
        inicio:        String(data.inicio ?? ""),
        duracion_min:  Number(data.duracion_min ?? 60),
      });
    case "reminder_24h":
      return renderReminder24h({
        ...base,
        servicio:      String(data.servicio ?? ""),
        inicio:        String(data.inicio ?? ""),
        duracion_min:  Number(data.duracion_min ?? 60),
      });
    case "booking_cancelled":
      return renderBookingCancelled({
        ...base,
        servicio: String(data.servicio ?? ""),
        inicio:   String(data.inicio ?? ""),
      });
    case "nueva_asignacion":
      return renderNuevaAsignacion({
        ...base,
        titulo_recurso: String(data.titulo_recurso ?? ""),
        tipo_recurso:   String(data.tipo_recurso ?? "recurso"),
      });
  }
}

Deno.serve(async (req) => {
  const corsHeaders = buildCorsHeaders(req.headers.get("origin"));
  const optionsResp = handleOptions(req);
  if (optionsResp) return optionsResp;

  if (req.method !== "POST") {
    return json({ error: "method_not_allowed" }, 405, corsHeaders);
  }

  // Autorización: requiere header Authorization (anon o service_role).
  // Validamos presencia; la RLS no aplica aquí porque usamos service_role.
  const authHeader = req.headers.get("authorization");
  if (!authHeader) {
    return json({ error: "unauthorized" }, 401, corsHeaders);
  }

  let payload: SendEmailRequest;
  try {
    payload = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400, corsHeaders);
  }

  if (!payload?.type) return json({ error: "missing_type" }, 400, corsHeaders);
  if (!payload.to_user_id && !payload.to_email) {
    return json({ error: "missing_recipient" }, 400, corsHeaders);
  }

  const admin = supabaseAdmin();

  // Resolver destinatario
  let profile: ProfileRow | null = null;
  let toEmail = payload.to_email ?? "";
  let toUserId: string | null = payload.to_user_id ?? null;

  if (toUserId) {
    const { data: p, error } = await admin
      .from("profiles")
      .select("id, email, display_name")
      .eq("id", toUserId)
      .maybeSingle();
    if (error) return json({ error: "profile_lookup_failed", detail: error.message }, 500, corsHeaders);
    if (!p) return json({ error: "profile_not_found" }, 404, corsHeaders);
    profile = p as ProfileRow;
    toEmail = profile.email;
  }

  if (!toEmail) return json({ error: "no_email_for_recipient" }, 422, corsHeaders);

  // Opt-in check
  if (toUserId) {
    const { data: prefs } = await admin
      .from("notificaciones_prefs")
      .select("welcome, booking_confirmed, booking_cancelled, reminder_24h, nueva_asignacion")
      .eq("user_id", toUserId)
      .maybeSingle<PrefsRow>();

    if (!prefsOptInForType(prefs, payload.type)) {
      await admin.from("emails_log").insert({
        email_type: payload.type,
        to_email:   toEmail,
        to_user_id: toUserId,
        cita_id:    payload.cita_id ?? null,
        status:     "skipped",
        error_message: "opted_out",
      });
      return json({ ok: true, skipped: "opted_out" }, 200, corsHeaders);
    }
  }

  // Insert pending (UNIQUE(dedupe_key) impide duplicados)
  const { data: logRow, error: insertErr } = await admin
    .from("emails_log")
    .insert({
      email_type: payload.type,
      to_email:   toEmail,
      to_user_id: toUserId,
      cita_id:    payload.cita_id ?? null,
      status:     "pending",
      attempts:   0,
    })
    .select("id")
    .maybeSingle();

  if (insertErr) {
    // 23505 = unique_violation → ya enviado en esta ventana
    if ((insertErr as any).code === "23505") {
      return json({ ok: true, deduped: true }, 200, corsHeaders);
    }
    return json({ error: "log_insert_failed", detail: insertErr.message }, 500, corsHeaders);
  }

  const rendered = renderFor(payload.type, payload.data ?? {}, profile);
  if (!rendered) return json({ error: "unknown_type" }, 400, corsHeaders);

  const result = await sendViaResend({
    from:      FROM_EMAIL,
    to:        toEmail,
    subject:   rendered.subject,
    html:      rendered.html,
    text:      rendered.text,
    reply_to:  REPLY_TO,
    tags:      [{ name: "type", value: payload.type }],
  });

  await admin
    .from("emails_log")
    .update({
      status:        result.ok ? "sent" : "failed",
      provider_id:   result.providerId ?? null,
      error_message: result.error ?? null,
      attempts:      result.attempts,
      sent_at:       result.ok ? new Date().toISOString() : null,
    })
    .eq("id", logRow!.id);

  return json(
    {
      ok: result.ok,
      provider_id: result.providerId,
      attempts: result.attempts,
      error: result.error,
    },
    result.ok ? 200 : 502,
    corsHeaders,
  );
});
